# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('model', models.TextField(blank=True)),
                ('category', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('material', models.TextField(blank=True)),
                ('url', models.URLField()),
                ('image', models.TextField()),
                ('site', models.URLField()),
                ('date', models.DateField()),
                ('currency', models.TextField()),
                ('price', models.TextField()),
                ('size', models.TextField(blank=True)),
                ('sale_price', models.TextField(blank=True)),
            ],
        ),
    ]
